use std::time::Instant;

use game_of_life::{
    cell::{Cell, CellState},
    grid::Grid,
    gui::View,
    life::LifeState,
};

// https://conwaylife.com/wiki/Pulsar
#[macroquad::main("Conway's Game of Life - Pulsar")]
async fn main() {
    let pulsar = vec![
        vec![Cell::new(CellState::Dead); 15],
        vec![
            Cell::new(CellState::Dead),
            Cell::new(CellState::Dead),
            Cell::new(CellState::Dead),
            Cell::new(CellState::Alive),
            Cell::new(CellState::Alive),
            Cell::new(CellState::Alive),
            Cell::new(CellState::Dead),
            Cell::new(CellState::Dead),
            Cell::new(CellState::Dead),
            Cell::new(CellState::Alive),
            Cell::new(CellState::Alive),
            Cell::new(CellState::Alive),
            Cell::new(CellState::Dead),
            Cell::new(CellState::Dead),
            Cell::new(CellState::Dead),
        ],
        vec![Cell::new(CellState::Dead); 15],
        vec![
            Cell::new(CellState::Dead),
            Cell::new(CellState::Alive),
            Cell::new(CellState::Dead),
            Cell::new(CellState::Dead),
            Cell::new(CellState::Dead),
            Cell::new(CellState::Dead),
            Cell::new(CellState::Alive),
            Cell::new(CellState::Dead),
            Cell::new(CellState::Alive),
            Cell::new(CellState::Dead),
            Cell::new(CellState::Dead),
            Cell::new(CellState::Dead),
            Cell::new(CellState::Dead),
            Cell::new(CellState::Alive),
            Cell::new(CellState::Dead),
        ],
        vec![
            Cell::new(CellState::Dead),
            Cell::new(CellState::Alive),
            Cell::new(CellState::Dead),
            Cell::new(CellState::Dead),
            Cell::new(CellState::Dead),
            Cell::new(CellState::Dead),
            Cell::new(CellState::Alive),
            Cell::new(CellState::Dead),
            Cell::new(CellState::Alive),
            Cell::new(CellState::Dead),
            Cell::new(CellState::Dead),
            Cell::new(CellState::Dead),
            Cell::new(CellState::Dead),
            Cell::new(CellState::Alive),
            Cell::new(CellState::Dead),
        ],
        vec![
            Cell::new(CellState::Dead),
            Cell::new(CellState::Alive),
            Cell::new(CellState::Dead),
            Cell::new(CellState::Dead),
            Cell::new(CellState::Dead),
            Cell::new(CellState::Dead),
            Cell::new(CellState::Alive),
            Cell::new(CellState::Dead),
            Cell::new(CellState::Alive),
            Cell::new(CellState::Dead),
            Cell::new(CellState::Dead),
            Cell::new(CellState::Dead),
            Cell::new(CellState::Dead),
            Cell::new(CellState::Alive),
            Cell::new(CellState::Dead),
        ],
        vec![
            Cell::new(CellState::Dead),
            Cell::new(CellState::Dead),
            Cell::new(CellState::Dead),
            Cell::new(CellState::Alive),
            Cell::new(CellState::Alive),
            Cell::new(CellState::Alive),
            Cell::new(CellState::Dead),
            Cell::new(CellState::Dead),
            Cell::new(CellState::Dead),
            Cell::new(CellState::Alive),
            Cell::new(CellState::Alive),
            Cell::new(CellState::Alive),
            Cell::new(CellState::Dead),
            Cell::new(CellState::Dead),
            Cell::new(CellState::Dead),
        ],
        vec![Cell::new(CellState::Dead); 15],
        vec![
            Cell::new(CellState::Dead),
            Cell::new(CellState::Dead),
            Cell::new(CellState::Dead),
            Cell::new(CellState::Alive),
            Cell::new(CellState::Alive),
            Cell::new(CellState::Alive),
            Cell::new(CellState::Dead),
            Cell::new(CellState::Dead),
            Cell::new(CellState::Dead),
            Cell::new(CellState::Alive),
            Cell::new(CellState::Alive),
            Cell::new(CellState::Alive),
            Cell::new(CellState::Dead),
            Cell::new(CellState::Dead),
            Cell::new(CellState::Dead),
        ],
        vec![
            Cell::new(CellState::Dead),
            Cell::new(CellState::Alive),
            Cell::new(CellState::Dead),
            Cell::new(CellState::Dead),
            Cell::new(CellState::Dead),
            Cell::new(CellState::Dead),
            Cell::new(CellState::Alive),
            Cell::new(CellState::Dead),
            Cell::new(CellState::Alive),
            Cell::new(CellState::Dead),
            Cell::new(CellState::Dead),
            Cell::new(CellState::Dead),
            Cell::new(CellState::Dead),
            Cell::new(CellState::Alive),
            Cell::new(CellState::Dead),
        ],
        vec![
            Cell::new(CellState::Dead),
            Cell::new(CellState::Alive),
            Cell::new(CellState::Dead),
            Cell::new(CellState::Dead),
            Cell::new(CellState::Dead),
            Cell::new(CellState::Dead),
            Cell::new(CellState::Alive),
            Cell::new(CellState::Dead),
            Cell::new(CellState::Alive),
            Cell::new(CellState::Dead),
            Cell::new(CellState::Dead),
            Cell::new(CellState::Dead),
            Cell::new(CellState::Dead),
            Cell::new(CellState::Alive),
            Cell::new(CellState::Dead),
        ],
        vec![
            Cell::new(CellState::Dead),
            Cell::new(CellState::Alive),
            Cell::new(CellState::Dead),
            Cell::new(CellState::Dead),
            Cell::new(CellState::Dead),
            Cell::new(CellState::Dead),
            Cell::new(CellState::Alive),
            Cell::new(CellState::Dead),
            Cell::new(CellState::Alive),
            Cell::new(CellState::Dead),
            Cell::new(CellState::Dead),
            Cell::new(CellState::Dead),
            Cell::new(CellState::Dead),
            Cell::new(CellState::Alive),
            Cell::new(CellState::Dead),
        ],
        vec![Cell::new(CellState::Dead); 15],
        vec![
            Cell::new(CellState::Dead),
            Cell::new(CellState::Dead),
            Cell::new(CellState::Dead),
            Cell::new(CellState::Alive),
            Cell::new(CellState::Alive),
            Cell::new(CellState::Alive),
            Cell::new(CellState::Dead),
            Cell::new(CellState::Dead),
            Cell::new(CellState::Dead),
            Cell::new(CellState::Alive),
            Cell::new(CellState::Alive),
            Cell::new(CellState::Alive),
            Cell::new(CellState::Dead),
            Cell::new(CellState::Dead),
            Cell::new(CellState::Dead),
        ],
        vec![Cell::new(CellState::Dead); 15],
    ];
    let mut state = LifeState::new(&Grid::new(&pulsar));

    let gui = View::new();

    let mut start = Instant::now();

    loop {
        gui.draw(&state).await;

        if start.elapsed().as_millis() > 500 {
            state = state.step();
            start = Instant::now();
        }
    }
}
